### ISSUE TITLE
Start time stop time not working correctly?

### ISSUE THREAD

**Issue by Klagio** [vpnmaster/homeassistant-custom-components#107]
If you see the code this lightingsm should be active only from midnight to sunrise (around 7am), but from the attributes it triggered at 10.20am, clearly after sunrise (the input_boolean which overrides its off)

```

  dining_room: 
    sensors: 
          - binary_sensor.pir_living_two
          - binary_sensor.pir_living_three
          - binary_sensor.pir_stairs_up
          - binary_sensor.pir_stairs_down
    entity: light.chandelier_one 
    service_data:
            brightness: 80
    start_time: '00:00:00'
    end_time: sunrise
    delay: 65
    sensor_type_duration: True
    overrides:
          - input_boolean.motion_dinimg_room_night
```

sensor_type: duration
delay: 65s
last_triggered_by: binary_sensor.pir_living_two
last_triggered_at: 2019-01-14 10:20:26.708325
expires_at: pending sensor
service_data: {
  "brightness": 80,
  "entity_id": "light.chandelier_one"
}
reset_at: 2019-01-14T10:20:31.383234
sensor_turned_off_at: 2019-01-14T10:20:43.063026
friendly_name: dining_room
icon: mdi:timer

**Comment by Klagio** [comment]
I don't understand if its me or the code, also this is not working. It says constrained, but the event its there (sunset is at 17.02 and now is 17:50


constrained | sensor_type: duration delay: 360s friendly_name: kitchen_evening icon: mdi:cancel
-- | --




 ```
 kitchen_evening: 
    sensors: binary_sensor.pir_kitchen
    entity: switch.light_kitchen
   # service_data:
   #         brightness: 80
    start_time: sunset
    end_time: '23:59:00'
    delay: 360
    sensor_type_duration: True
    overrides:
          - input_boolean.motion_kitchen_evening
```
