### ISSUE TITLE
Broadlink IR Media Player channels?

### ISSUE THREAD

**Issue by vMeph** [vpnmaster/homeassistant-custom-components#47]
how to go about Broadlink IR Media Player chanels?
i wanted to set chanels with more decimal numbers like 100, how would i set this code, from my understanding this will need a delay betwen numbers
how would i set this on the lg.ini file?
could you give a exemple?

thanks

**Comment by psyciknz** [comment]
Having just put it down ,I'm wondering this also.

**Comment by vpnmaster** [comment]
could you please update the media player component and try combine 2 commands separated with "|" character?
Example:
[sources]
Channel 1 = JgAaAB4dOh4cHh4dHB4cHh0dHh0cHh0dHTw6AA0FAAAAAAAAAAAAAAAAAAA=|JgAcAB8cPBweHB8bHxweHB4cHxweHB4cHxweOh4ADQUAAAAAAAAAAAAAAAA=

**Comment by vMeph** [comment]
works very good!!!
thanks for the update....

is there any way to integrate this component with Alexa dot eco?

for exemple to integrate alexa with broadlink rm i need to make scripts:
ex:

```
  discovery:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.tecla1
      - delay:
          seconds: 0
      - service: switch.turn_on
        data:
          entity_id: switch.tecla0
      - delay:
          seconds: 0
      - service: switch.turn_on
        data:
          entity_id: switch.tecla0

    switches:
      tecla0:
        friendly_name: 'tecla0'
        command_on: 'JgA8ABsgNz03PTg8OCAaPRogOB8bAAuTGx84PTc9Nz04Hxs9GiA3IBsAC5MbHzg9Nz04PDgfGz0aIDcgGwANBQAAAAAAAAAAAAAAAA=='
      tecla1:
        friendly_name: 'tecla1'
        command_on: 'JgBIABsfGx8cHzc9ODw4HxsfGyAaPRogGwALdRsfGx8bHzg8OD03IBsfGx8bPBsfGwALdhsfGx8bHzg8OD03IBsfGx8bPBsfGwANBQ=='
```
  in this exemple im calling dicovery channel 100  

my question is how could i call in a script the channels from lg.ini file?
