### ISSUE TITLE
How to turn on/turn off AC using component?

### ISSUE THREAD

**Issue by mouth4war** [vpnmaster/homeassistant-custom-components#7]
Is it even possible? Do we have to continue using a separate switch for turn_on/off or does the component do any operations on power state?

my LG AC codes https://pastebin.com/P7bYqUbp

**Comment by tatunts** [comment]
Hello @mouth4war, how are you?

I have a window AC set up with this custom component. It is possible to set off command, works like a charm. To turn it on, I just send set the operation mode and it turns on.

Here is my config:
```
  - platform: broadlink
    name: Ar condicionado do trabalho
    host: 192.168.1.60
    mac: '34:EA:34:A4:5F:2F'
    ircodes_ini: 'broadlink_climate_codes/consul.ini'
    min_temp: 18
    max_temp: 30
    target_temp: 24
    temp_sensor: sensor.muvrh_temperature
    default_operation: idle
    default_fan_mode: low
    customize:
      operations:
        - idle
        - cool
        - heat
        - auto
      fan_modes:
        - low
        - mid
        - high
```
Here is the .ini file used: [Consul commands](https://github.com/vpnmaster/homeassistant-custom-components/blob/master/broadlink_climate_codes/consul.ini)

Hope it helps!
